import 'package:flutter/material.dart';

abstract class ColorTheme {
  static const Color appInfoBackgroundColor = Color(0xFF00334E);
  static       Color appInfoButtonBackground = Colors.black.withOpacity(0.00);
  static const Color appInfoButtonBorder = Colors.white;
  static const Color appInfoElevatedButtonColor = Colors.white;
  static const Color loginPageBackgroundColor = Color(0xFF00334E);
  static const Color loginFormButtonForegroundColor = Colors.white;
  static const Color loginFormButtonBackgroundColor = Colors.white;
  static const Color loginFormButtonBorder = Colors.black;
  static const Color loginFormEnabledBorder = Colors.white;
  static const Color loginFormFocusedBorder = Colors.white;
  static const Color loginFormFocusedErrorBorder = Colors.red;
  static const Color loginFormErrorBorder = Colors.red;
  static const Color registerPageBackgroundColor = Color(0xFF00334E);
  static const Color registerFormButtonForegroundColor = Colors.white;
  static const Color registerFormButtonBackgroundColor = Colors.white;
  static const Color registerFormButtonBorderColor = Colors.black;
  static const Color snackBarBackgroundColor = Colors.red;
  static const Color registerFormEnabledBorder = Colors.white;
  static const Color registerFormFocusedBorder = Colors.white;
  static const Color registerFormFocusedErrorBorder = Colors.red;
  static const Color registerFormErrorBorder = Colors.red;
  static const Color chartsTabDateButtonColor = Colors.white;
  static const Color chartsTabCardColor = Colors.white;
  static const Color navbarSelectedItemColor = Colors.deepOrange;
  static const Color statsPageTabColor = Colors.white;
  static const Color statsPageTabIconColor = Color(0xFF00334E);
  static const Color statsPageIndicatorColor = Color(0xFFFED049);
  static const Color statsPageSlowIconColor = Colors.green;
  static const Color statsPageMediumIconColor = Colors.orange;
  static const Color statsPageFastIconColor = Colors.red;
  static const Color trainingPageRoadColor = Colors.purple;
  static const Color trainingPageGpsFixIconColor = Color(0xFF00334E);
  static const Color trainingPageStartButtonColor = Color(0xFFFED049);
  static const Color trainingPageButtonIconColor = Colors.white;
  static const Color trainingPageButtonIconPlayColor = trainingPageButtonIconColor;
  static const Color trainingPageButtonIconPauseColor = trainingPageButtonIconColor;
  static const Color trainingPageButtonIconStopColor = trainingPageButtonIconColor;
  static const Color trainingPagePauseButtonColor = Color(0xFF00334E);
  static const Color trainingPageStopButtonColor = Color(0xFF00334E);
}